# Generated by Django 5.2.16 on 2026-08-13 18:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def eliminar_tokens_legacy(apps, schema_editor):
    Token = apps.get_model("authtoken", "Token")
    Token.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.RunPython(eliminar_tokens_legacy, migrations.RunPython.noop),
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=False, help_text='Obliga a reemplazar la contraseña temporal en el siguiente acceso.', verbose_name='debe cambiar la contraseña'),
        ),
        migrations.CreateModel(
            name='ControlIntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_normalizado', models.CharField(max_length=254)),
                ('direccion_ip', models.CharField(max_length=45)),
                ('ventana_iniciada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('fallos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueos_acumulados', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'control de intentos de acceso',
                'verbose_name_plural': 'controles de intentos de acceso',
                'indexes': [models.Index(fields=['bloqueado_hasta'], name='login_bloqueo_idx'), models.Index(fields=['ultimo_intento_en'], name='login_ultimo_idx')],
                'constraints': [models.UniqueConstraint(fields=('email_normalizado', 'direccion_ip'), name='cuentas_login_email_ip_unico')],
            },
        ),
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login_exitoso', 'Inicio de sesión exitoso'), ('login_fallido', 'Inicio de sesión fallido'), ('login_bloqueado', 'Inicio de sesión bloqueado'), ('logout', 'Cierre de sesión'), ('clave_cambiada', 'Contraseña cambiada'), ('clave_restablecida', 'Contraseña restablecida por administración'), ('sesiones_revocadas', 'Sesiones revocadas'), ('cuenta_desactivada', 'Cuenta desactivada'), ('cuenta_desbloqueada', 'Cuenta desbloqueada')], max_length=40)),
                ('email_normalizado', models.CharField(blank=True, max_length=254)),
                ('direccion_ip', models.CharField(blank=True, max_length=45)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de seguridad',
                'verbose_name_plural': 'eventos de seguridad',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TokenDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispositivo_id', models.CharField(max_length=128)),
                ('nombre_dispositivo', models.CharField(blank=True, max_length=160)),
                ('secreto_hash', models.CharField(editable=False, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_en', models.DateTimeField()),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_dispositivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión de dispositivo',
                'verbose_name_plural': 'sesiones de dispositivos',
                'ordering': ['-ultimo_uso_en'],
                'indexes': [models.Index(fields=['expira_en'], name='token_expira_idx'), models.Index(fields=['revocado_en'], name='token_revocado_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'dispositivo_id'), name='cuentas_token_usuario_dispositivo_unico')],
            },
        ),
    ]
