from django.urls import path

from . import views
from .api import (
    CambioClaveApiView,
    CicloCerrarApiView,
    CicloDetalleApiView,
    CiclosApiView,
    EspeciesApiView,
    HealthApiView,
    JornadaAnularApiView,
    JornadaDetalleApiView,
    JornadasApiView,
    LecturasSensorLoteApiView,
    LoginApiView,
    LogoutApiView,
    MeApiView,
    MovimientoAnularApiView,
    MovimientoDetalleApiView,
    MovimientosApiView,
    PiscinasApiView,
    PrediccionCicloApiView,
    SemaforosApiView,
)

app_name = "monitoreo"

urlpatterns = [
    path("api/v1/health/", HealthApiView.as_view(), name="api_health"),
    path("api/v1/auth/login/", LoginApiView.as_view(), name="api_login"),
    path("api/v1/auth/logout/", LogoutApiView.as_view(), name="api_logout"),
    path("api/v1/auth/cambiar-clave/", CambioClaveApiView.as_view(), name="api_cambiar_clave"),
    path("api/v1/auth/me/", MeApiView.as_view(), name="api_me"),
    path("api/v1/catalogos/especies/", EspeciesApiView.as_view(), name="api_especies"),
    path("api/v1/catalogos/piscinas/", PiscinasApiView.as_view(), name="api_piscinas"),
    path("api/v1/ciclos/", CiclosApiView.as_view(), name="api_ciclos"),
    path("api/v1/ciclos/prediccion/", PrediccionCicloApiView.as_view(), name="api_ciclo_prediccion"),
    path("api/v1/ciclos/<uuid:ciclo_id>/", CicloDetalleApiView.as_view(), name="api_ciclo_detalle"),
    path("api/v1/ciclos/<uuid:ciclo_id>/cerrar/", CicloCerrarApiView.as_view(), name="api_ciclo_cerrar"),
    path("api/v1/jornadas/", JornadasApiView.as_view(), name="api_jornadas"),
    path("api/v1/jornadas/<uuid:jornada_id>/", JornadaDetalleApiView.as_view(), name="api_jornada_detalle"),
    path("api/v1/jornadas/<uuid:jornada_id>/anular/", JornadaAnularApiView.as_view(), name="api_jornada_anular"),
    path("api/v1/movimientos/", MovimientosApiView.as_view(), name="api_movimientos"),
    path("api/v1/movimientos/<uuid:movimiento_id>/", MovimientoDetalleApiView.as_view(), name="api_movimiento_detalle"),
    path("api/v1/movimientos/<uuid:movimiento_id>/anular/", MovimientoAnularApiView.as_view(), name="api_movimiento_anular"),
    path("api/v1/sensores/lecturas/lote/", LecturasSensorLoteApiView.as_view(), name="api_sensor_lecturas_lote"),
    path("api/v1/semaforos/", SemaforosApiView.as_view(), name="api_semaforos"),
    path("login/", views.login_view, name="login"),
    path("cambiar-clave-inicial/", views.cambiar_clave_inicial, name="cambiar_clave_inicial"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("piscinas/<uuid:piscina_id>/", views.piscina_detalle, name="piscina_detalle"),
    path("piscinas/<uuid:piscina_id>/ciclos/nuevo/", views.ciclo_abrir, name="ciclo_abrir"),
    path("ciclos/<uuid:ciclo_id>/cerrar/", views.ciclo_cerrar, name="ciclo_cerrar"),
    path("piscinas/<uuid:piscina_id>/registros/nuevo/", views.registro_nuevo, name="registro_nuevo"),
    path("registros/<uuid:registro_id>/", views.registro_detalle, name="registro_detalle"),
]
