# Generated by Django 5.2.16 on 2026-07-12 00:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuicultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80, unique=True, verbose_name='nombre visible')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_acuicultor', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'acuicultor',
                'verbose_name_plural': 'acuicultores',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='Piscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('peces', 'Peces'), ('lombrices', 'Lombrices')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('acuicultores', models.ManyToManyField(blank=True, related_name='piscinas', to='monitoreo.acuicultor')),
            ],
            options={
                'verbose_name': 'piscina',
                'verbose_name_plural': 'piscinas',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH')),
                ('nitrato', models.DecimalField(decimal_places=2, help_text='mg/L', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('amonio', models.DecimalField(decimal_places=2, help_text='mg/L', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('nitrito', models.DecimalField(decimal_places=2, help_text='mg/L', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('poblacion_estimada', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('acuicultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to='monitoreo.acuicultor')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='monitoreo.piscina')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MuestraPez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('peso_gramos', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='peso (g)')),
                ('talla_centimetros', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='talla (cm)')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_peces', to='monitoreo.registro')),
            ],
            options={
                'verbose_name': 'muestra de pez',
                'verbose_name_plural': 'muestras de peces',
                'ordering': ['id'],
            },
        ),
    ]
