# Generated by Django 5.2.16 on 2026-08-20 19:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_adaptar_agua_al_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriacambio',
            name='entidad',
            field=models.CharField(choices=[('JORNADA', 'Jornada'), ('MOVIMIENTO', 'Movimiento'), ('CICLO', 'Ciclo')], max_length=20),
        ),
        migrations.CreateModel(
            name='CicloProductivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=10)),
                ('iniciado_en', models.DateTimeField()),
                ('poblacion_inicial', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duracion_estimada_meses', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('observaciones_apertura', models.TextField(blank=True)),
                ('fuente', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android')], default='WEB', max_length=12)),
                ('dispositivo_id', models.CharField(blank=True, max_length=120)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('destino_cierre', models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('CONSUMO', 'Consumo'), ('TRASLADO', 'Traslado'), ('MORTALIDAD_TOTAL', 'Mortalidad total'), ('OTRO', 'Otro')], max_length=20)),
                ('poblacion_final', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_total_cosechado_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones_cierre', models.TextField(blank=True)),
                ('prediccion_poblacion_final', models.PositiveIntegerField(blank=True, null=True)),
                ('prediccion_min', models.PositiveIntegerField(blank=True, null=True)),
                ('prediccion_max', models.PositiveIntegerField(blank=True, null=True)),
                ('prediccion_tasa', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('prediccion_ciclos_usados', models.PositiveSmallIntegerField(default=0)),
                ('prediccion_confianza', models.CharField(choices=[('SIN_DATOS', 'Sin datos'), ('MUY_BAJA', 'Muy baja'), ('BAJA', 'Baja'), ('MEDIA', 'Media')], default='SIN_DATOS', max_length=12)),
                ('prediccion_metodo_version', models.CharField(blank=True, max_length=80)),
                ('prediccion_calculada_en', models.DateTimeField(blank=True, null=True)),
                ('prediccion_datos_hasta', models.DateTimeField(blank=True, null=True)),
                ('prediccion_origen', models.CharField(choices=[('SERVIDOR', 'Servidor'), ('CACHE_ANDROID', 'Caché Android')], default='SERVIDOR', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('autor_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_abiertos', to='monitoreo.acuicultor')),
                ('autor_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_cerrados', to='monitoreo.acuicultor')),
                ('especie', models.ForeignKey(help_text='Instantánea histórica de la especie permanente de la piscina.', on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_productivos', to='monitoreo.especie')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='monitoreo.piscina')),
                ('piscina_destino_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_recibidos_al_cierre', to='monitoreo.piscina')),
            ],
            options={
                'verbose_name': 'ciclo productivo',
                'verbose_name_plural': 'ciclos productivos',
                'ordering': ['-iniciado_en', '-numero'],
            },
        ),
        migrations.AddField(
            model_name='jornadaregistro',
            name='ciclo',
            field=models.ForeignKey(blank=True, help_text='Temporalmente nullable para migrar datos de desarrollo anteriores a 1.5.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='monitoreo.cicloproductivo'),
        ),
        migrations.AddField(
            model_name='movimientopoblacion',
            name='ciclo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='monitoreo.cicloproductivo'),
        ),
        migrations.AddField(
            model_name='movimientopoblacion',
            name='ciclo_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='monitoreo.cicloproductivo'),
        ),
        migrations.CreateModel(
            name='DispositivoSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('selector', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('secreto_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('activo', models.BooleanField(default=False, help_text='Debe permanecer desactivado hasta habilitar formalmente la telemetría.')),
                ('instalado_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_uso_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_sensor', to='monitoreo.piscina')),
            ],
            options={
                'verbose_name': 'dispositivo sensor',
                'verbose_name_plural': 'dispositivos sensores',
                'ordering': ['piscina', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medida_en', models.DateTimeField()),
                ('recibida_en', models.DateTimeField(auto_now_add=True)),
                ('oxigeno_disuelto_mg_l', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(60)])),
                ('turbidez_ntu', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('calidad', models.CharField(choices=[('COMPLETA', 'Completa'), ('PARCIAL', 'Parcial'), ('INVALIDA', 'Inválida')], max_length=10)),
                ('detalle_calidad', models.CharField(blank=True, max_length=500)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecturas_sensor', to='monitoreo.cicloproductivo')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='monitoreo.dispositivosensor')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas_sensor', to='monitoreo.piscina')),
            ],
            options={
                'verbose_name': 'lectura de sensor',
                'verbose_name_plural': 'lecturas de sensores',
                'ordering': ['-medida_en', '-recibida_en'],
            },
        ),
        migrations.AddIndex(
            model_name='cicloproductivo',
            index=models.Index(fields=['piscina', 'estado'], name='ix_ciclo_piscina_estado'),
        ),
        migrations.AddIndex(
            model_name='cicloproductivo',
            index=models.Index(fields=['piscina', '-iniciado_en'], name='ix_ciclo_piscina_inicio'),
        ),
        migrations.AddConstraint(
            model_name='cicloproductivo',
            constraint=models.UniqueConstraint(fields=('piscina', 'numero'), name='uq_ciclo_numero_piscina'),
        ),
        migrations.AddConstraint(
            model_name='cicloproductivo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('piscina',), name='uq_ciclo_activo_piscina'),
        ),
        migrations.AddConstraint(
            model_name='cicloproductivo',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_ciclo_version_positiva'),
        ),
        migrations.AddConstraint(
            model_name='cicloproductivo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('autor_cierre__isnull', True), ('cerrado_en__isnull', True), ('destino_cierre', ''), ('estado', 'ACTIVO'), ('poblacion_final__isnull', True)), ('estado', 'ANULADO'), models.Q(('autor_cierre__isnull', False), ('cerrado_en__isnull', False), ('estado', 'CERRADO'), ('poblacion_final__isnull', False)), _connector='OR'), name='ck_ciclo_campos_cierre_estado'),
        ),
        migrations.AddIndex(
            model_name='lecturasensor',
            index=models.Index(fields=['piscina', '-medida_en'], name='ix_lectura_piscina_fecha'),
        ),
        migrations.AddIndex(
            model_name='lecturasensor',
            index=models.Index(fields=['dispositivo', '-medida_en'], name='ix_lectura_dispositivo_fecha'),
        ),
        migrations.AddConstraint(
            model_name='lecturasensor',
            constraint=models.CheckConstraint(condition=models.Q(('oxigeno_disuelto_mg_l__isnull', False), ('temperatura_c__isnull', False), ('turbidez_ntu__isnull', False), _connector='OR'), name='ck_lectura_al_menos_un_valor'),
        ),
    ]
