# Generated by Django 5.2.16 on 2026-09-01 23:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0004_agua_valores_numericos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamaLombrices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cama de lombrices',
                'verbose_name_plural': 'camas de lombrices',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloLombricultura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=10)),
                ('iniciado_en', models.DateTimeField()),
                ('conteo_inicial', models.PositiveIntegerField()),
                ('observaciones_apertura', models.TextField(blank=True)),
                ('fuente', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android')], default='WEB', max_length=12)),
                ('dispositivo_id', models.CharField(blank=True, max_length=120)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('conteo_final', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ciclo de lombricultura',
                'verbose_name_plural': 'ciclos de lombricultura',
                'ordering': ['-iniciado_en', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='PerfilSemaforoEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('provisional', models.BooleanField(default=True)),
                ('supuesto_biologico', models.TextField(blank=True)),
                ('fuentes', models.JSONField(blank=True, default=list)),
                ('ph_critico_bajo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph_ideal_bajo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph_ideal_alto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph_critico_alto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nitrito_amarillo_desde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nitrito_rojo_desde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nitrato_amarillo_desde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nitrato_rojo_desde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amoniaco_total_amarillo_desde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amoniaco_total_rojo_desde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nh3_amarillo_desde', models.DecimalField(decimal_places=5, max_digits=10)),
                ('nh3_rojo_desde', models.DecimalField(decimal_places=5, max_digits=10)),
                ('temperatura_critica_baja_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperatura_ideal_baja_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperatura_ideal_alta_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperatura_critica_alta_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('oxigeno_rojo_menor_que_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('oxigeno_verde_desde_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('turbidez_amarillo_desde_ntu', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('turbidez_rojo_desde_ntu', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil de semáforo por especie',
                'verbose_name_plural': 'perfiles de semáforo por especie',
            },
        ),
        migrations.CreateModel(
            name='RegistroLombricultura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capturada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('recibida_en', models.DateTimeField(auto_now_add=True)),
                ('ph_suelo', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH del suelo')),
                ('conteo_lombrices', models.PositiveIntegerField(help_text='Conteo observado de lombrices; no es una estimación automática.')),
                ('observaciones', models.TextField(blank=True)),
                ('fuente', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android')], default='WEB', max_length=12)),
                ('dispositivo_id', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('COMPLETO', 'Completo'), ('ANULADO', 'Anulado')], default='COMPLETO', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('modificada_en', models.DateTimeField(auto_now=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'registro de lombricultura',
                'verbose_name_plural': 'registros de lombricultura',
                'ordering': ['-capturada_en', '-creada_en'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='piscina',
            name='ck_piscina_peces_con_especie',
        ),
        migrations.AddField(
            model_name='auditoriacambio',
            name='comunidad',
            field=models.ForeignKey(blank=True, help_text='Se conserva nullable solo para auditorías históricas sin tenant recuperable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='monitoreo.comunidad'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='id_publico',
            field=models.UUIDField(blank=True, editable=False, help_text='Identificador estable que puede exponerse a clientes sin revelar la PK interna.', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriacambio',
            name='entidad',
            field=models.CharField(choices=[('JORNADA', 'Jornada'), ('MOVIMIENTO', 'Movimiento'), ('CICLO', 'Ciclo'), ('CICLO_LOMBRIZ', 'Ciclo de lombricultura'), ('REGISTRO_LOMBRIZ', 'Registro de lombricultura')], max_length=20),
        ),
        migrations.AlterField(
            model_name='piscina',
            name='tipo',
            field=models.CharField(choices=[('PECES', 'Peces')], default='PECES', editable=False, help_text='Campo legado fijado a PECES; las lombrices se gestionan en camas.', max_length=20),
        ),
        migrations.AddField(
            model_name='camalombrices',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camas_lombrices', to='monitoreo.comunidad'),
        ),
        migrations.AddField(
            model_name='ciclolombricultura',
            name='autor_apertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_lombricultura_abiertos', to='monitoreo.acuicultor'),
        ),
        migrations.AddField(
            model_name='ciclolombricultura',
            name='autor_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_lombricultura_cerrados', to='monitoreo.acuicultor'),
        ),
        migrations.AddField(
            model_name='ciclolombricultura',
            name='cama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='monitoreo.camalombrices'),
        ),
        migrations.AddField(
            model_name='perfilsemaforoespecie',
            name='especie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_semaforo', to='monitoreo.especie'),
        ),
        migrations.AddField(
            model_name='registrolombricultura',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_lombricultura_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrolombricultura',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_lombricultura', to='monitoreo.acuicultor'),
        ),
        migrations.AddField(
            model_name='registrolombricultura',
            name='cama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='monitoreo.camalombrices'),
        ),
        migrations.AddField(
            model_name='registrolombricultura',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='monitoreo.ciclolombricultura'),
        ),
        migrations.AddConstraint(
            model_name='camalombrices',
            constraint=models.UniqueConstraint(fields=('comunidad', 'codigo'), name='uq_cama_codigo_comunidad'),
        ),
        migrations.AddConstraint(
            model_name='ciclolombricultura',
            constraint=models.UniqueConstraint(fields=('cama', 'numero'), name='uq_ciclo_lombriz_numero_cama'),
        ),
        migrations.AddConstraint(
            model_name='ciclolombricultura',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('cama',), name='uq_ciclo_lombriz_activo_cama'),
        ),
        migrations.AddConstraint(
            model_name='ciclolombricultura',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_ciclo_lombriz_version'),
        ),
        migrations.AddConstraint(
            model_name='ciclolombricultura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('autor_cierre__isnull', True), ('cerrado_en__isnull', True), ('conteo_final__isnull', True), ('estado', 'ACTIVO')), ('estado', 'ANULADO'), models.Q(('autor_cierre__isnull', False), ('cerrado_en__isnull', False), ('conteo_final__isnull', False), ('estado', 'CERRADO')), _connector='OR'), name='ck_ciclo_lombriz_cierre_estado'),
        ),
        migrations.AddIndex(
            model_name='registrolombricultura',
            index=models.Index(fields=['cama', '-capturada_en'], name='ix_reg_lombriz_cama_fecha'),
        ),
        migrations.AddIndex(
            model_name='registrolombricultura',
            index=models.Index(fields=['estado'], name='ix_reg_lombriz_estado'),
        ),
        migrations.AddConstraint(
            model_name='registrolombricultura',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_registro_lombriz_version'),
        ),
    ]
